[package]
name = "aow-im"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
tempfile = "3.20"

[dev-dependencies]
axum.workspace = true
